version: "3.3"
services:
  redis:
    image: redis:6.0.7
    container_name: redis
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
    - 6379:6379
  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: redis insight
    restart: always
    ports:
      - 8001:8001
    volumes:
    - redis insight volume data:/db

volumes:
  redis_volume_data:
  redis insight volume data: